## Lattice_Start_Simulations
# 
#========================================================	
# ---
### title: Lattice starting point simulations
# author: Marie Gilbertson
# date: "09/07/2018"
#---
# ##  Preamble	
# 
# What this code does:
# 1. Simulates BCRW movement for population of 100 individuals for 90 days with starting points on a lattice. Lattice 
# is generated by setting the distance between starting points; all distances between starting points are the same for 
# a given simulation, but between simulations vary between based on average home range size (1-2x the 
# radius of an average home range for given BCRW parameter set). 
#
# This script does not include contact detection or sampling; this code can be found in "Random_Start_Simulations.R"
# and is equivalent for all population spatial configurations.


##### Clear Environment
remove(list=ls())


#### Load R libraries	
library(CircStats)
library(adehabitatLT) 
library(fields)
library(reshape)
library(sp)
library(lubridate)
library(gdata) 
library(adehabitatHR) 
library(doParallel)
library(foreach)
library(plyr)
library(doRNG)


#---------------------------------------------------------
### Set simulation parameters based on array-id
#---------------------------------------------------------

# set array-id for this simulation
sim <- as.numeric(commandArgs(TRUE[1]))
sim.seed <- 14000 + sim  # ensure unique seeds for lattice start simulations



#---------------------------------------------------------------------------------------------
### Read in functions to simulate BCRW movement trajectories for a population of individuals
#---------------------------------------------------------------------------------------------

#Weighted circular mean calculation
source("w.circ.mean.R")

# BCRW simulation function
source("BCRW_sim.R")


#-------------------------------------------------------------------------------------------
### Set parameters and simulate BCRW movement trajectories for a population of individuals
#-------------------------------------------------------------------------------------------
#

##################################
######### Set Parameters #########
##################################

### read in lattice starting locations ###
# Files available on GitHub
starts <- get(load("Lattice Sims Starting Locations_H15.Rdata"))

nsims <- 100 # number of individuals to simulate. MUST BE A SQUARE NUMBER
x.sep <- y.sep <- starts[sim] # separation between starting locations
final.duration <- 90 # duration (in days) of simualation
duration <- 7 + final.duration # account for initial "burn-in" period

h <- 15 # scaling parameter for step length
rho <- 0.8 # bias correlation parameter (0-1, where 0 -> unbiased, uncorrelated random walk, and 1 -> biased, deterministic movement)
b <- 0.01  # bias strength parameter (how fast bias increases or decreases)
c <- 0.3  # bias distance decay parameter (0 = no bias due to distance, >0 = bias increases w/distance, <0 = bias decreases w/distance)
##################################
##################################

# create list of starting points
x.start <- NULL
y.start <- NULL
for(i in 1:(sqrt(nsims))){
  x.start.temp <- x.sep*i
  x.start.temp2 <- as.matrix(rep(x.start.temp, sqrt(nsims)), ncol=1)
  x.start <- rbind(x.start, x.start.temp2)
  for(j in 1:(sqrt(nsims))){
    y.start.temp <- y.sep*j
    y.start <- rbind(y.start, y.start.temp)
  }
}

# run the movement simulations, including setting up parallelization
cl <- makeCluster(3) 
registerDoParallel(cl)


clusterEvalQ(cl, {
  library(CircStats)
  library(adehabitatLT)
  library(lubridate)
  library(foreach)
})

# sim.seed ensures reproducibility and unique simulations, even with parallelization
all.sims <- foreach(n=1:nsims, .combine=rbind, .options.RNG=sim.seed) %dorng% {
  x.sim <- x.start[n]
  y.sim <- y.start[n]
  simulation <- BCRW_sim(n=duration*60*24, h = h, rho = rho, y0=c(x.sim, y.sim), b = b, c = c)  
  simulation$id <- paste(n)
  simulation
}

stopCluster(cl)


# remove the first 7 days as "burn in" period
all.sims$step.id <- seq(1, 139681, 1)
remove.id <- seq(1, 10080, 1)
all.sims <- all.sims[!(all.sims$step.id %in% remove.id),]


#---------------------------------------------------------------------------------------
### Proceed with contact detection and sampling, found in "Random_Start_Simulations.R"
#---------------------------------------------------------------------------------------
